listener 1883
allow_anonymous true

listener 8883
cafile C:/Ufape/5 periodo/redes/iiot-mqtt-simulation/certs/ca.crt
certfile C:/Ufape/5 periodo/redes/iiot-mqtt-simulation/certs/server.crt
keyfile C:/Ufape/5 periodo/redes/iiot-mqtt-simulation/certs/server.key
allow_anonymous true